openapi: 3.0.0
info:
  title: Converter API
  description: Converter Audio Video Image PDF API
  version: 0.1.9
servers:
  - url: http://localhost:9292/api/v1.0
    description: Converter server

paths:
  /compiler/:
    post:
      summary: Upload a file
      requestBody:
        required: true
        content:
          compile_files:
            schema:
              type: object
              properties:
                file:
                  name: file
                  type: string
                  format: binary
                language:
                  name: language
                  type: string
                version:
                  name: version
                  type: string
          

      responses:
        '200':
          description: File uploaded successfully
        '400':
          description: Invalid input
        '500':
          description: Internal server error

