openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8818/api/v1/interview
    description: Optional server description, e.g. Main (production) server
  - url: http://localhost:9090/api/v1/role
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /interviews:
    get:
      summary: Returns a list of interviews.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /roles:
    get:
      summary: Returns a list of roles.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string